name: Week 3 Stage Thinking

on:
  push:

jobs:

  build:
    runs-on: ubuntu-latest

    steps:
      - name: Build Stage
        run: echo "Building Application"

  test:
    needs: build

    runs-on: ubuntu-latest

    steps:
      - name: Test Stage
        run: echo "Running Tests"

  artifact:
    needs: test

    runs-on: ubuntu-latest

    steps:
      - name: Artifact Stage
        run: echo "Creating Artifact"
