name: Day 5 CI pipeline
on:
  push:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Generate build output
        run: |
          echo "Build successful" > build-info.txt
          echo "Created by GitHub Actions" >> build-info.txt

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: build-output
          path: build-info.txt


    

